# Generated by Django 5.0.2 on 2024-03-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=20)),
                ('Emp_id', models.IntegerField()),
                ('Designation', models.CharField(max_length=20)),
                ('Date_of_joining', models.DateField()),
                ('Department', models.CharField(max_length=25)),
                ('Salary_package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Experience', models.FloatField()),
            ],
        ),
    ]
