# Generated by Django 5.0.2 on 2024-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_news_rename_date_of_joining_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Occation', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='Occation',
            field=models.TextField(max_length=100),
        ),
    ]
